name: Run Java 22 JAR

on:
  push:
    branches:
      - main

jobs:
  run-jar:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Can be 'zulu', 'adopt', 'oracle', etc.
        java-version: '22'

    - name: Run JAR file
      run: java -jar path/to/your-jar-file.jar
